name: Build and Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.5.0

      - name: Install deps
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: false
          dist_dir: dist
